name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run migrations
      run: |
        source .env && python manage.py makemigrations
      env:
        DATABASE_URL: postgres://test_user:test_password@db:5432/test_db


    - name: Apply migrations
      run: |
        source .env && python manage.py migrate
      env:
        DATABASE_URL: postgres://test_user:test_password@db:5432/test_db

       
    - name: Run tests
      run: |
        source .env && python manage.py test
      env:
        DATABASE_URL: postgres://test_user:test_password@db:5432/test_db

