name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DATABASE_URL: psql://postgres:postgres@localhost:5432/test
jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run migrations
      run: |
        python manage.py makemigrations

    - name: Apply migrations
      run: |
        python manage.py migrate
       
    - name: Run tests
      run: |
        python manage.py test
        
    - name: Runing Lint (pylint)
      run: |
        pylint --rcfile=pylintrc $(git ls-files -- '*.py' ':!:**/migrations/*.py')

